- name: Install docker-compose dependencies (pip)
  apt:
    name: python3-pip
    state: present
    force_apt_get: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present

